[project]
name = "repo2docker-example"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "jupyter-repo2docker>=2024.7.0",
]
